# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjudgementNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'adjudgement_natures',
            },
        ),
        migrations.CreateModel(
            name='AdjudgementRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtr_year', models.IntegerField()),
                ('year', models.IntegerField()),
                ('records_count', models.IntegerField()),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'adjudgement_records',
            },
        ),
        migrations.CreateModel(
            name='AdjudgementRecordAdjudgementNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records_count', models.SmallIntegerField()),
                ('adjudgement_nature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.AdjudgementNature')),
                ('adjudgement_record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.AdjudgementRecord')),
            ],
            options={
                'db_table': 'adjudgement_record_adjudgement_nature_entries',
            },
        ),
        migrations.CreateModel(
            name='AdjudgementRecordLegislationSubarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records_count', models.SmallIntegerField()),
                ('adjudgement_record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.AdjudgementRecord')),
            ],
            options={
                'db_table': 'adjudgement_record_legislation_subarea_entries',
            },
        ),
        migrations.CreateModel(
            name='CustomerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtr_year', models.IntegerField()),
                ('year', models.IntegerField()),
                ('sum_money', models.DecimalField(decimal_places=2, max_digits=13)),
                ('sum_contracts', models.IntegerField()),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'customer_records',
            },
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('identification', models.CharField(max_length=48)),
                ('public_official', models.BooleanField()),
            ],
            options={
                'db_table': 'end_users',
            },
        ),
        migrations.CreateModel(
            name='LegislationSubarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'legislation_subareas',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted_address', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=128)),
                ('reg_number', models.IntegerField()),
                ('building_number', models.CharField(max_length=128)),
                ('postal_code', models.CharField(max_length=16)),
                ('municipality', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=64)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Organization')),
            ],
            options={
                'db_table': 'organization_address_entries',
            },
        ),
        migrations.CreateModel(
            name='OrganizationEndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_since', models.DateField()),
                ('last_change', models.DateField()),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.EndUser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Organization')),
            ],
            options={
                'db_table': 'organization_end_user_entries',
            },
        ),
        migrations.CreateModel(
            name='OrganizationIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipo', models.IntegerField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Organization')),
            ],
            options={
                'db_table': 'organization_identifier_entries',
            },
        ),
        migrations.CreateModel(
            name='OrganizationName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Organization')),
            ],
            options={
                'db_table': 'organization_name_entries',
            },
        ),
        migrations.CreateModel(
            name='SupplierRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtr_year', models.IntegerField()),
                ('year', models.IntegerField()),
                ('sum_money', models.DecimalField(decimal_places=2, max_digits=13)),
                ('sum_contracts', models.IntegerField()),
                ('url', models.URLField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Organization')),
            ],
            options={
                'db_table': 'supplier_records',
            },
        ),
        migrations.AddField(
            model_name='customerrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Organization'),
        ),
        migrations.AddField(
            model_name='adjudgementrecordlegislationsubarea',
            name='legislation_subarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.LegislationSubarea'),
        ),
        migrations.AddField(
            model_name='adjudgementrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Organization'),
        ),
    ]
