# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjudgementNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'adjudgement_nature',
            },
        ),
        migrations.CreateModel(
            name='AdjudgementRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtr_year', models.IntegerField()),
                ('year', models.IntegerField()),
                ('records_count', models.IntegerField()),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'adjudgement_record',
            },
        ),
        migrations.CreateModel(
            name='AdjudgementRecord_AdjudgementNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records_count', models.SmallIntegerField()),
                ('adjudgement_record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.AdjudgementRecord')),
            ],
            options={
                'db_table': 'adjudgement_record_adjudgement_nature',
            },
        ),
        migrations.CreateModel(
            name='AdjudgementRecord_LegislationSubarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records_count', models.SmallIntegerField()),
                ('adjudgement_record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.AdjudgementRecord')),
            ],
            options={
                'db_table': 'adjudgement_record_legislation_subarea',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtr_year', models.IntegerField()),
                ('year', models.IntegerField()),
                ('sum_money', models.DecimalField(decimal_places=2, max_digits=13)),
                ('sum_contracts', models.IntegerField()),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('identification', models.CharField(max_length=48)),
                ('public_official', models.BooleanField()),
            ],
            options={
                'db_table': 'end_user',
            },
        ),
        migrations.CreateModel(
            name='LegislationSubarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'adjudgement_legislation_subarea',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Organization_EndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_since', models.DateField()),
                ('last_change', models.DateField()),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.EndUser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Organization')),
            ],
            options={
                'db_table': 'organization_end_user',
            },
        ),
        migrations.CreateModel(
            name='OrganizationIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipo', models.IntegerField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Organization')),
            ],
            options={
                'db_table': 'organization_identifier',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtr_year', models.IntegerField()),
                ('year', models.IntegerField()),
                ('sum_money', models.DecimalField(decimal_places=2, max_digits=13)),
                ('sum_contracts', models.IntegerField()),
                ('url', models.URLField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Organization')),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Organization'),
        ),
        migrations.AddField(
            model_name='adjudgementrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Organization'),
        ),
    ]
